version: '3.8'

services:
  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: service:redis
    environment:
      - AZURE_FUNCTIONS_ENVIRONMENT=Development
      - ML_ENDPOINT=http://localhost:8000/predict
      - REDIS_CONNECTION_STRING=localhost:6379
    
  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: